# Generated by Django 2.2.10 on 2020-10-11 17:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('a', '관리자'), ('g', '참여자')], max_length=1)),
                ('type', models.CharField(choices=[('r', '요청'), ('c', '생성')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField()),
                ('available_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('user_limit', models.IntegerField(default=2)),
                ('introduction', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='wating', max_length=12)),
                ('meeting', models.ManyToManyField(through='meeting.Meeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_id', to='meeting.Room'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('room_id', 'user_id')},
        ),
    ]
