# Generated by Django 2.2.10 on 2020-10-17 00:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', '신청'), ('c', '생성')], max_length=1)),
                ('is_accepted', models.CharField(choices=[('a', '수락'), ('r', '거절'), ('w', '대기')], default='w', max_length=1)),
                ('user_role', models.CharField(choices=[('inviter', 'Inviter'), ('invitee', 'Invitee')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('a', '관리자'), ('g', '참여자')], max_length=1)),
                ('type', models.CharField(choices=[('p', '신청'), ('c', '생성')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('available_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('user_limit', models.IntegerField(default=2)),
                ('introduction', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('w', 'wating'), ('m', 'matched'), ('a', 'active'), ('c', 'canceled')], default='w', max_length=1)),
            ],
        ),
    ]
