# Generated by Django 2.2.10 on 2020-10-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20201017_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsparticipation',
            name='user_role',
            field=models.CharField(choices=[('inviter', 'Inviter'), ('invitee', 'Invitee')], max_length=7),
        ),
    ]
