# Generated by Django 2.2.10 on 2020-10-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20201012_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('w', 'wating'), ('m', 'matched')], default='w', max_length=1),
        ),
    ]
