# Generated by Django 2.2.10 on 2020-10-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20201012_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='meeting_date',
            field=models.DateField(null=True),
        ),
    ]
