# Generated by Django 2.2.10 on 2020-10-12 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0005_auto_20201012_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='meeting',
            field=models.ManyToManyField(related_name='meeting', through='meeting.Meeting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('room', 'user')},
        ),
    ]
