# Generated by Django 2.2.10 on 2020-10-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20201012_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('w', 'wating'), ('m', 'matched'), ('a', 'active')], default='w', max_length=1),
        ),
    ]
