# Generated by Django 2.2.10 on 2020-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_remove_room_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('p', '신청'), ('c', '생성')], max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('w', 'wating'), ('m', 'matched'), ('a', 'active'), ('c', 'canceled')], default='w', max_length=1),
        ),
    ]
