# Generated by Django 2.2.10 on 2020-10-17 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgData', models.ImageField(upload_to='')),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChineseZodiac',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('name', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email_info', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=5)),
                ('end_date', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ZodiacCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.IntegerField()),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_from_zodiad', to='etcInformation.ChineseZodiac')),
                ('_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_to_zodiad', to='etcInformation.ChineseZodiac')),
            ],
        ),
        migrations.CreateModel(
            name='StarCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.IntegerField()),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_from_star', to='etcInformation.Star')),
                ('_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_to_star', to='etcInformation.Star')),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='compatibility',
            field=models.ManyToManyField(through='etcInformation.StarCompatibility', to='etcInformation.Star'),
        ),
        migrations.CreateModel(
            name='MbtiCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.IntegerField()),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_from_mbti', to='etcInformation.Mbti')),
                ('_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_to_mbti', to='etcInformation.Mbti')),
            ],
        ),
        migrations.AddField(
            model_name='mbti',
            name='compatibility',
            field=models.ManyToManyField(through='etcInformation.MbtiCompatibility', to='etcInformation.Mbti'),
        ),
        migrations.AddField(
            model_name='chinesezodiac',
            name='compatibility',
            field=models.ManyToManyField(through='etcInformation.ZodiacCompatibility', to='etcInformation.ChineseZodiac'),
        ),
    ]
