# Generated by Django 2.2.10 on 2020-10-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etcInformation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbticompatibility',
            old_name='from_mbti',
            new_name='_from',
        ),
        migrations.RenameField(
            model_name='mbticompatibility',
            old_name='to_mbti',
            new_name='_to',
        ),
        migrations.RenameField(
            model_name='starcompatibility',
            old_name='from_star',
            new_name='_from',
        ),
        migrations.RenameField(
            model_name='starcompatibility',
            old_name='to_star',
            new_name='_to',
        ),
        migrations.RenameField(
            model_name='zodiaccompatibility',
            old_name='from_zodiac',
            new_name='_from',
        ),
        migrations.RenameField(
            model_name='zodiaccompatibility',
            old_name='to_zodiac',
            new_name='_to',
        ),
    ]
