# Generated by Django 2.2.10 on 2020-10-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='friends',
            name='type',
            field=models.CharField(choices=[('f', '친구'), ('b', '차단')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etcInformation.Animal', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=40, verbose_name='학교'),
        ),
    ]
