# Generated by Django 2.2.10 on 2020-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201010_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='end_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='star',
            name='start_date',
            field=models.CharField(max_length=5),
        ),
    ]
