# Generated by Django 2.2.10 on 2020-11-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chinese_zodiac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etcInformation.ChineseZodiac', verbose_name='띠'),
        ),
    ]
