# Generated by Django 2.2.10 on 2020-10-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201010_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star',
            field=models.ForeignKey(default='천칭자리', on_delete=django.db.models.deletion.CASCADE, to='user.Star', verbose_name='별자리'),
            preserve_default=False,
        ),
    ]
