# Generated by Django 2.2.10 on 2020-10-11 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20201012_0238'),
        ('user', '0004_user_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', '신청'), ('c', '생성')], max_length=1)),
                ('is_accepted', models.CharField(choices=[('a', '수락'), ('r', '거절')], max_length=1)),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from_user', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_room_id', to='meeting.Room')),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_uesr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room_id', 'from_user_id', 'to_user_id')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='friends_participation',
            field=models.ManyToManyField(through='user.FriendsParticipation', to=settings.AUTH_USER_MODEL),
        ),
    ]
