# Generated by Django 2.2.10 on 2020-10-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20201012_2301'),
        ('user', '0005_auto_20201012_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsparticipation',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friendsparticipation',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='friendsparticipation',
            old_name='to_user_id',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='friendsparticipation',
            unique_together={('room', 'from_user', 'to_user')},
        ),
    ]
