# Generated by Django 2.2.10 on 2020-10-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etcInformation', '0001_initial'),
        ('user', '0006_auto_20201012_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chinese_zodiac',
            field=models.ForeignKey(default='쥐', on_delete=django.db.models.deletion.CASCADE, to='etcInformation.ChineseZodiac', verbose_name='별자리'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendsparticipation',
            name='is_accepted',
            field=models.CharField(choices=[('a', '수락'), ('r', '거절'), ('w', '대기')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etcInformation.Mbti', verbose_name='mbti 성향'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etcInformation.Animal', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etcInformation.School', verbose_name='학교'),
        ),
        migrations.AlterField(
            model_name='user',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etcInformation.Star', verbose_name='별자리'),
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Mbti',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
