# Generated by Django 2.2.10 on 2020-10-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201013_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chinese_zodiac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etcInformation.ChineseZodiac', verbose_name='별자리'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etcInformation.Mbti', verbose_name='mbti 성향'),
        ),
        migrations.AlterField(
            model_name='user',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etcInformation.Star', verbose_name='별자리'),
        ),
    ]
