# Generated by Django 2.2.10 on 2020-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=6, verbose_name='성별'),
        ),
    ]
