# Generated by Django 2.2.10 on 2020-10-16 12:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_auto_20201016_1233'),
        ('user', '0011_auto_20201014_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsparticipation',
            name='invitee_user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='request_invitee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendsparticipation',
            name='inviter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_inviter_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='friendsparticipation',
            unique_together={('room', 'inviter_user', 'invitee_user')},
        ),
        migrations.RemoveField(
            model_name='friendsparticipation',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendsparticipation',
            name='to_user',
        ),
    ]
